server:
  port: ${AA_PORT:8082}
  servlet:
    context-path: /

spring:
  kafka:
    bootstrap-servers: ${AA_KAFKA_SERVERS:10.28.19.161:9092,10.28.19.161:9083}
    consumer:
      auto-offset-reset: ${AA_KAFKA_AUTO_OFFSET_RESET:latest}
      enable-auto-commit: ${AA_KAFKA_ENABLE_AUTO_COMMIT:false}
      auto-commit-interval: ${AA_KAFKA_AUTO_COMMIT:100}
      key-serializer: ${AA_KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${AA_KAFKA_VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      group-id: ${AA_KAFKA_GROUP_ID:paranora}
