server:
  port: ${AA_PORT:8083}
  servlet:
    context-path: /

spring:
  kafka:
    bootstrap-servers: ${AA_KAFKA_SERVERS:10.4.99.4:9092,10.28.19.196:9082}
    producer:
      batch-size: ${AA_KAFKA_BATCH_SIZE:1}
      retries: ${AA_KAFKA_RETRY:1}
      buffer-memory: ${AA_KAFKA_BUFFER_MEM:33554432}
      compressionType:  ${AA_KAFKA_COMPRESS_TYPE:none}
      key-serializer: ${AA_KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${AA_KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
    consumer:
      auto-offset-reset: ${AA_KAFKA_AUTO_OFFSET_RESET:latest}
      enable-auto-commit: ${AA_KAFKA_ENABLE_AUTO_COMMIT:false}
      auto-commit-interval: ${AA_KAFKA_AUTO_COMMIT:100}
      key-serializer: ${AA_KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-serializer: ${AA_KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonDeserializer}
      group-id: ${AA_KAFKA_GROUP_ID:paranora-group}
      client-id: ${AA_KAFKA_CLIENT_ID:paranora}
