#spring:
#  profiles:
#    active: kafka,kafka-producer,kafka-rongyun-private-message-producer,kafka-rongyun-private-message-service,rongyun

#spring:
#  profiles:
#    active: kafka,kafka-producer,kafka-rongyun-group-message-producer,kafka-rongyun-group-message-service,rongyun

#spring:
#  profiles:
#    active: kafka,kafka-rongyun-private-message-consumer,kafka-rongyun-private-message-service,rongyun

#spring:
#  profiles:
#    active: kafka,kafka-consumer,kafka-rongyun-private-message-consumer,rongyun

spring:
  profiles:
    active: kafka,kafka-consumer,${AA_KAFKA_CONSUMER_TYPE:null},rongyun
  cloud:
    consul:
      host: 10.28.19.194
      port: 8500
      enabled: false
      discovery:
        enabled: true
        register: true
        port: ${local.port}
        tags: urlprefix-/${spring.application.name}
        hostname: ${spring.application.name}
        ip-address: ${local.ip}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${local.ip}:${local.port}
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 10s
        health-check-timeout: 10s
        health-check-url: http://${local.ip}:${local.port}/actuator/health

#spring:
#  profiles:
#    active: kafka,kafka-producer,rongyun


rongyun:
  appKey: ${AA_RONGYUN_APPKEY:123321}
  appSecret: ${AA_RONGYUN_APPSECRET:123321}
