server:
  port: ${AA_PORT:8080}
  servlet:
    context-path: /

spring:
  kafka:
    bootstrap-servers: ${AA_KAFKA_SERVERS:10.28.19.161:9092,10.28.19.161:9083}
    producer:
      batch-size: ${AA_KAFKA_BATCH_SIZE:1}
      retries: ${AA_KAFKA_RETRY:1}
      buffer-memory: ${AA_KAFKA_BUFFER_MEM:33554432}
      compressionType:  ${AA_KAFKA_COMPRESS_TYPE:none}
      key-serializer: ${AA_KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${AA_KAFKA_VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
